name: Build and Deploy NovoAdmin

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Archive production artifacts
        run: |
          tar czf deploy.tar.gz dist

      - name: Copy to server and deploy
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "deploy.tar.gz"
          target: "/www/wwwroot/"

      - name: SSH and extract
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /www/wwwroot
            rm -rf NovoAdmin
            mkdir NovoAdmin
            tar xzf deploy.tar.gz -C NovoAdmin
            rm deploy.tar.gz
