name: Deploy VitePress site to Pages

on:
  # 在 main 分支上的推送触发部署
  push:
    branches: [main]
  # 允许手动触发部署
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时进行一次部署
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 不是必需的，但可能对某些插件有用
      
      # 1. 首先安装 pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      
      # 2. 然后设置 Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      # 3. 安装依赖
      - name: Install dependencies
        run: pnpm install
      
      - name: Build
        run: pnpm run docs:build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  # 部署工作
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    uses: peaceiris/actions-gh-pages@v3
    with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/.vitepress/dist